// angular/src/app/modules/third/components/pokemon-list/pokemon-list.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { IPokemon } from 'src/app/modules/types';

@Component({
  selector: 'app-pokemon-list',
  templateUrl: './pokemon-list.component.html',
  styleUrls: ['./pokemon-list.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PokemonListComponent {

  @Input() selected: IPokemon | null = null;

  @Input() pokemons: IPokemon[] = [];

  @Output() selectItem: EventEmitter<IPokemon> = new EventEmitter();

  getSprite(item: IPokemon): string {
    return `${item.id.toString().padStart(3, '0')}MS.png`;
  }

}

// react/components/AppTittle/third/PokemonList.tsx
import React, { Component } from 'react';
import { IPokemon } from '../../../data/types';

type PokemonListProps = {
    selected?: IPokemon | null;
    pokemons?: IPokemon[];
    selectItem?: (pokemon: IPokemon) => void;
};

class PokemonList extends Component<PokemonListProps> {

    getSprite(pokemon: IPokemon): string {
        return `${pokemon.id.toString().padStart(3, '0')}MS.png`;
    }

    render() {
        const {
            selected = null,
            pokemons = [],
            selectItem = () => { },
        } = this.props;

        return <div className="pokemon-list-component">
            {pokemons.map((p, i) => <div key={i} onClick={() => selectItem(p)}
                className={`d-flex justify-content-start align-items-center item ${p.id === selected?.id ? 'selected' : ''}`}>
                <img src={`/pokemon/sprites/${this.getSprite(p)}`} />
                <div>
                    <p className="m-0">#{p.id}. {p.name.english}</p>
                </div>
            </div>)}
        </div>;
    }
}

export default PokemonList;
