// angular/src/app/modules/second/components/pokemon-list/pokemon-list.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { IPokemon } from 'src/app/modules/types';
import pokemons from 'src/app/data/pokedex.json';

@Component({
  selector: 'app-pokemon-list',
  templateUrl: './pokemon-list.component.html',
  styleUrls: ['./pokemon-list.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PokemonListComponent {

  @Input() selected: IPokemon | null = null;

  @Output() selectItem: EventEmitter<IPokemon> = new EventEmitter();

  pokemons: IPokemon[] = pokemons;

  getSprite(item: IPokemon): string {
    return `${item.id.toString().padStart(3, '0')}MS.png`;
  }

}

<div *ngFor="let item of pokemons" class="d-flex justify-content-start align-items-center item"
    [ngClass]="{selected: item.id === selected?.id}" (click)="selectItem.emit(item)">
    <img src="/assets/pokemon/sprites/{{getSprite(item)}}" />
    <div>
        <p class="m-0">#{{item.id}}. {{item.name.english}}</p>
    </div>
</div>

// react/components/AppTittle/second/PokemonList.tsx
import React, { Component } from 'react';
import { IPokemon } from '../../../data/types';
import pokemons from '../../../data/pokedex.json';

type PokemonListProps = {
    selected: IPokemon | null;
    selectItem?: (pokemon: IPokemon) => void;
};

class PokemonList extends Component<PokemonListProps> {

    pokemons: IPokemon[] = pokemons;

    getSprite(pokemon: IPokemon): string {
        return `${pokemon.id.toString().padStart(3, '0')}MS.png`;
    }

    render() {
        const {
            selected = null,
            selectItem = () => { },
        } = this.props;

        return <div className="pokemon-list-component">
            {pokemons.map((p, i) => <div key={i} onClick={() => selectItem(p)}
                className={`d-flex justify-content-start align-items-center item ${p.id === selected?.id ? 'selected' : ''}`}>
                <img src={`/pokemon/sprites/${this.getSprite(p)}`} />
                <div>
                    <p className="m-0">#{p.id}. {p.name.english}</p>
                </div>
            </div>)}
        </div>;
    }
}

export default PokemonList;
